// <auto-generated />
using System;
using InterviewCoach.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterviewCoach.Migrations
{
    [DbContext(typeof(InterviewCoachContext))]
    [Migration("20260406191700_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("InterviewCoach.Models.PracticeAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AttemptDate")
                        .HasColumnType("TEXT");

                    b.Property<float>("AttemptScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.ToTable("PracticeAttempts");
                });

            modelBuilder.Entity("InterviewCoach.Models.StarRubric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Guidance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GuidanceDetail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StarRubrics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Guidance = "Set the scene. Where were you, what was the context, why did it matter?",
                            GuidanceDetail = "A strong situation is specific, concise, and immediately relevant. It names the project, team, or context clearly. A weak situation is vague, too long, or could apply to anyone.",
                            Section = "Situation"
                        },
                        new
                        {
                            Id = 2,
                            Guidance = "What was your specific responsibility?",
                            GuidanceDetail = "A strong task statement clearly defines what YOU owned, not the team. It sets up why your actions mattered. A weak task is generic, uses 'we', or is hard to distinguish from the situation.",
                            Section = "Task"
                        },
                        new
                        {
                            Id = 3,
                            Guidance = "What did YOU do? Use I not we.",
                            GuidanceDetail = "Strong actions are specific, sequential, and show judgment. They demonstrate the competency being assessed. Weak actions are vague, use 'we', or describe process without showing your thinking.",
                            Section = "Action"
                        },
                        new
                        {
                            Id = 4,
                            Guidance = "What was the outcome? Quantify if possible.",
                            GuidanceDetail = "Strong results are quantified, tied directly to your actions, and include reflection or learning. Weak results are vague ('it went well'), unconnected to your actions, or missing entirely.",
                            Section = "Result"
                        });
                });

            modelBuilder.Entity("InterviewCoach.Models.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .HasColumnType("TEXT");

                    b.Property<float>("ActionScore")
                        .HasColumnType("REAL");

                    b.Property<string>("AuthorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoachingFeedback")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.Property<float>("ResultScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Situation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("SituationScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Task")
                        .HasColumnType("TEXT");

                    b.Property<float>("TaskScore")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("InterviewCoach.Models.PracticeAttempt", b =>
                {
                    b.HasOne("InterviewCoach.Models.Story", "Story")
                        .WithMany("PracticeAttempts")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("InterviewCoach.Models.Story", b =>
                {
                    b.Navigation("PracticeAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
